### ISSUE TITLE
Property 'isMulti' does not exist on type 'CustomChoiceComponent'

### ISSUE THREAD

**Issue by cfsilence** [NetanelBasal/nb-choices#1]
### Are you in the right place?

  * For issues or feature requests related to the choices library go to [Choices.js](https://github.com/jshjohnson/Choices/issues)
  * For general technical questions, post a question on [StackOverflow](http://stackoverflow.com/) tagged appropriately.
  
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x ] Bug report  
[ ] Feature request
[ ] Documentation issue or request
</code></pre>

## Current behavior

When I run `ng build --prod` on an Angular 4 application which uses `nb-choices` I receive the following error:

```
ERROR in ng:///C:/Users/558848/Documents/Projects/[my project]/node_modules/nb-choices/dist/components/custom-choice.component.d.ts.CustomChoiceCompo
nent.html (12,21): Property 'isMulti' does not exist on type 'CustomChoiceComponent'.
```

## Expected behavior

I expect the build not to fail.

## Minimal reproduction of the problem with instructions

Add this package to an Angular application and run `ng build --prod`

## Environment

<pre><code>
Angular version: 4.2.4

Browser:
- [x ] Chrome (desktop) version 63.0.3239.132
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
Others:

</code></pre>

**Comment by cfsilence** [comment]
Can you please advise when you receive this issue?  My build is currently failing on this issue.  Thanks!

I believe this fixes the issue, but I do not have rights to push a branch to this repo:

https://github.com/cfsilence/nb-choices/blob/fix-isMulti/src/components/custom-choice.component.ts

**Comment by NetanelBasal** [comment]
Added the `Input()`, can you confirm it's working, please? (1.0.3-beta)

**Comment by cfsilence** [comment]
I'm still getting the error:

```
ERROR in ng:///C:/Users/558848/Documents/Projects/GMM/codebase/gmm-prototype-ui/node_modules/nb-choices/dist/components/custom-choice.component.d.ts.CustomChoiceCompo
nent.html (12,21): Property 'isMulti' does not exist on type 'CustomChoiceComponent'.
```

When running ng build --prod

**Comment by cfsilence** [comment]
Just to confirm, i'm testing this with 

`"nb-choices": "^1.0.3-beta",`

At the moment

**Comment by cfsilence** [comment]
You  might also need to fix `src/components/nb-choices.component.ts`.

**Comment by NetanelBasal** [comment]
typescript is not complaining about anything in my code, can you elaborate more, please?
