### ISSUE TITLE
Property 'isMulti' does not exist on type 'CustomChoiceComponent' - prod build

### ISSUE THREAD

**Issue by ganeshkantu** [NetanelBasal/nb-choices#3]
### Are you in the right place?

  * For issues or feature requests related to the choices library go to [Choices.js](https://github.com/jshjohnson/Choices/issues)
  * For general technical questions, post a question on [StackOverflow](http://stackoverflow.com/) tagged appropriately.
  
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Feature request
[ ] Documentation issue or request
</code></pre>

## Current behavior

ng build --prod throws the below error:
ERROR in node_modules\nb-choices\dist\components\custom-choice.component.d.ts.CustomChoiceComponent.html(12,13): : Property 'isMulti' does not exist on type 'CustomChoiceComponent'.

## Expected behavior

ng build --prod should work as expected

## Minimal reproduction of the problem with instructions

build app with --prod

## Environment

<pre><code>
Angular version: 5.2.1

Browser:
- [x] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
Others:

</code></pre>

**Comment by NetanelBasal** [comment]
Version 1.0.0 - fixed.

**Comment by ganeshkantu** [comment]
Still getting the same issue - with 1.0.0

**Comment by NetanelBasal** [comment]
Are you sure? isMulti doesn't exist anymore, check this file:
https://github.com/NetanelBasal/nb-choices/blob/master/src/components/custom-choice.component.ts

**Comment by ganeshkantu** [comment]
I see that. But in the dist I see a lot of references to isMulti. I deleted my node_modules folder and redid npm install too. Same error:

ERROR in node_modules\nb-choices\dist\components\custom-choice.component.d.ts.CustomChoiceComponent.html(12,13): : Property 'isMulti' does not exist on type 'CustomChoiceComponent'.

**Comment by NetanelBasal** [comment]
I can't find even one place that isMulti is mentioned. Can you elaborate more, please?

**Comment by ganeshkantu** [comment]
I deleted nb-choices, did npm cache clean and then did an install again. This is what I see in the dist:


```
import { OnInit, TemplateRef } from '@angular/core';
import * as Choices from 'choices.js';
export declare abstract class ChoiceTemplate implements OnInit {
    contextExp: {
        $implicit: any;
    };
    classNames: Choices.ClassNames;
    data: Choices.Choice;
    tpl: TemplateRef<any>;
    withCheckbox: boolean;
    config: Choices.Options;
    isMultiple: boolean;
    readonly abstract getClass: any;
    ngOnInit(): void;
}
export declare class CustomChoiceComponent extends ChoiceTemplate implements OnInit {
    readonly getClass: {
        [x: number]: any;
        'choices__item--selected': any;
        'choices__placeholder': any;
    };
}
export declare class CustomChoiceSelectedComponent extends ChoiceTemplate implements OnInit {
    isMulti: boolean;
    readonly getClass: {
        [x: number]: any;
        'choices__placeholder': any;
    };
}

```

**Comment by NetanelBasal** [comment]
try 1.0.2, please.

**Comment by ganeshkantu** [comment]
Looks like this worked. My prod build is crashing with java heap space issues now. Will report back once I get that working.
