### ISSUE TITLE
Cannot find name 'CHOICES_CONFIG'"

### ISSUE THREAD

**Issue by SonOfCrypto** [NetanelBasal/nb-choices#4]
Thank you for this module!

Everything works fine with Angular CLI, except the "providers: [{provide: CHOICES_CONFIG, useValue: { removeItems: false }}]" part.

I am getting the error "error: Cannot find name 'CHOICES_CONFIG'". Can you tell me what I am doing wrong?

THX

**Comment by NetanelBasal** [comment]
I will investigate and let you know, thanks!

**Comment by SonOfCrypto** [comment]
thx! I guess I figured it out my self. I forgot importing the config. 🙈
```
import { NbChoicesModule, CHOICES_CONFIG } from 'nb-choices';
```
