### ISSUE TITLE
Is there an option for 

### ISSUE THREAD

**Issue by astr0sl0th** [NetanelBasal/nb-choices#7]
## I'm submitting a...
<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Feature request
[x] Documentation issue or request
</code></pre>

## Current behavior
Could only find documentation for choice template

## Expected behavior
Expected to find documentation for item template

## Minimal reproduction of the problem with instructions
N/A

## What is the motivation / use case for changing the behavior?
N/A

## Environment
N/A

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
Others:
I was hoping to find some documentation for item templates as well.

**Comment by NetanelBasal** [comment]
https://stackblitz.com/edit/nb-choices?file=app%2Fhello.component.ts. Check out the first example.

**Comment by astr0sl0th** [comment]
@NetanelBasal Perfect thank you.
