### ISSUE TITLE
Compile issues - Namespace 'Choices' has no exported member 'ClassNames'

### ISSUE THREAD

**Issue by astr0sl0th** [NetanelBasal/nb-choices#9]
### Are you in the right place?

  * For issues or feature requests related to the choices library go to [Choices.js](https://github.com/jshjohnson/Choices/issues)
  * For general technical questions, post a question on [StackOverflow](http://stackoverflow.com/) tagged appropriately.
  
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Feature request
[ ] Documentation issue or request
</code></pre>

## Current behavior
When trying to compile I am recieing the following error:
```
ERROR in node_modules/nb-choices/dist/components/custom-choice.component.d.ts(7,25): error TS2694: Namespace 'Choices' has no exported member 'ClassNames'.
node_modules/nb-choices/dist/components/custom-choice.component.d.ts(8,19): error TS2694: Namespace 'Choices' has no exported member 'Choice'.
```

## Expected behavior
Should compile without errors

## Minimal reproduction of the problem with instructions
yarn add nb-choices
ng serve

## Environment

<pre><code>
Angular version: 6

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
Others:

</code></pre>

**Comment by NetanelBasal** [comment]
Thanks for the report. It doesn't support yes Angular 6. I will do it in the future or would love to accept a PR.

**Comment by NetanelBasal** [comment]
#8

**Comment by astr0sl0th** [comment]
@NetanelBasal  It is technically all working as I am using it with angular 6 just throws that error on compile

**Comment by NetanelBasal** [comment]
Is it happening only in production?

**Comment by astr0sl0th** [comment]
No just when building or ng serve I haven't tried production but I would imagine it would be the same result. Looks to be just some type errors nothing on an angular based level

**Comment by NetanelBasal** [comment]
Very wired, cause no one report this kind of issue, can you help investigate, please?

**Comment by astr0sl0th** [comment]
Of course. I am currently doing some digging now. I am using nb-choices in two angular projects both versions 6+ and both have the same errors

**Comment by NetanelBasal** [comment]
Ok, thank, let me know.

**Comment by astr0sl0th** [comment]
The root problem seems to be in custom-choice.component.d.ts

```
classNames: Choices.classNames; <- Choice.classNames does not exist on Choices
data: Choices.Choice; <- Choices.Choice does not exist on Choices
```

To silence these compile errors I have set any as fix not sure if there is a better way in dealing with this but it works for now...
```
classNames: any
data: any;
```

**Comment by NetanelBasal** [comment]
Ok, thanks, I will look into it later.

**Comment by NetanelBasal** [comment]
Changed it in 1.0.3, can you confirm it's working please?

**Comment by astr0sl0th** [comment]
Is it on NPM?

**Comment by NetanelBasal** [comment]
yes

**Comment by astr0sl0th** [comment]
I can confirm that your update has fixed the errors I was getting. Thank you :)
